sudo: required

language: python

python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
#  - "3.5"
#  - "3.5-dev"
#  - "nightly"

services:
  - docker

env:
  global:
    - W3AF_HOST=localhost
    - W3AF_PORT=5000
    - W3AF_TARGETS=http://localhost:80


before_install:
  - docker pull andresriancho/w3af-api
  - docker run --detach --publish ${W3AF_PORT}:5000 andresriancho/w3af-api
  - while ! curl --silent localhost:${W3AF_PORT} | grep docs.w3af.org; do sleep 1; done

  - docker pull citizenstig/dvwa
  - docker run --detach --publish 80:80 citizenstig/dvwa


install:
  - python setup.py install


script:
  #- nosetests
  - python -m unittest -v
