sudo: required

language: python

python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
#  - "3.5"
#  - "3.5-dev"
#  - "nightly"

services:
  - docker

 
before_install:
  - docker pull andresriancho/w3af-api
  - docker run --detach --publish 5000:5000 andresriancho/w3af-api
  - curl localhost:5000

install:
  - python setup.py install


script:
  - nosetests
